# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 22:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='文章名')),
                ('url', models.URLField(blank=True, unique=True, verbose_name='主页地址')),
                ('weights', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1, message='不能小于%(limit_value)s.'), django.core.validators.MaxValueValidator(100, message='不能大于%(limit_value)s.')], verbose_name='权重')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('total_page', models.IntegerField(default=1, verbose_name='当前页数')),
                ('is_end', models.BooleanField(default=False, verbose_name='是否完结')),
                ('author', models.CharField(blank=True, max_length=256, null=True, verbose_name='作者信息')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='分类')),
                ('url', models.URLField(blank=True, unique=True, verbose_name='主页地址')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('weights', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1, message='不能小于%(limit_value)s.'), django.core.validators.MaxValueValidator(100, message='不能大于%(limit_value)s.')], verbose_name='权重')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['-weights', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='章节名')),
                ('url', models.URLField(blank=True, unique=True, verbose_name='所在分页地址')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('page', models.IntegerField(default=1, verbose_name='所在分页')),
                ('floor', models.IntegerField(default=0, verbose_name='所在楼层')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Article', verbose_name='所属文章')),
            ],
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='网站名')),
                ('url', models.URLField(blank=True, unique=True, verbose_name='官网')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('weights', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1, message='不能小于%(limit_value)s.'), django.core.validators.MaxValueValidator(100, message='不能大于%(limit_value)s.')], verbose_name='权重')),
            ],
            options={
                'verbose_name': '站点',
                'verbose_name_plural': '站点',
                'ordering': ['-weights', '-id'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.WebSite', verbose_name='所属站点'),
        ),
        migrations.AddField(
            model_name='category',
            name='sub_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.Category', verbose_name='父分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Category', verbose_name='所属分类'),
        ),
    ]
