# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='文章描述'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='章节内容'),
        ),
    ]
