# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20171130_2310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-weights', '-id'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': '章节', 'verbose_name_plural': '章节'},
        ),
    ]
