# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20171130_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ['-weights', 'id'], 'verbose_name': '站点', 'verbose_name_plural': '站点'},
        ),
        migrations.AddField(
            model_name='article',
            name='site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='book.WebSite', verbose_name='所属站点'),
        ),
    ]
