# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20171203_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='url',
            field=models.URLField(blank=True, verbose_name='所在分页地址'),
        ),
    ]
