# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20171218_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('floor', 'create_time'), 'verbose_name': '章节', 'verbose_name_plural': '章节'},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='url',
        ),
    ]
