# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 22:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20171219_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='total_chapter',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='不能小于%(limit_value)s.')], verbose_name='文章章节数'),
        ),
    ]
